### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by rened**
Hi,
there exists an MNIST package - makes it easier to focus on the important part in the example.

### CODE REVIEW

**Comment by rened** [comment]
ah, and just fyi: https://github.com/JuliaLang/julia/issues/10487
(this is not a problem with tsne itself)

**Comment by lejon** [comment]
Great thanks for that! I HATE that I don't get any notifications from Github when there are comments and pull requests! What do I miss in the GitHub settings, I think that I have enabled all notifications, but I must have missed something.

**Comment by rened** [comment]
No problem ;-) Hm, that is odd, I get notifications for everything that happens on my repos.  You could try to manually "Watch" your own repo at the top right, perhaps that helps.

**Comment by lejon** [comment]
Good suggestion, I'll try that!

**Pull request merged**
