### PR TITLE
Add project.toml

### PR DESCRIPTION
**Pull request by simonschoelly**
This PR replaces the REQUIRE files with a Project.toml.

In addition:
- Bump version to 1.3.0
- Set required Julia version to 1.5.0
- Make the example files work again

### CODE REVIEW

**Comment by lejon** [comment]
Thanks a bunch!

**Comment by simonschoelly** [comment]
You have closed this without merging?

May I ask if you don't plan to make this package work with the current Julia version? Or are you planning to do in another way?

**Comment by lejon** [comment]
Really?! That was a mistake then. Admittedly I did it on the phone while traveling so perhaps I mucked up, the intention was certainly to merge it! I’ll have a look!

BR
-Leif

**Comment by lejon** [comment]
Ok, I realise what the problem was, there was a "confirm merge" that I apparently missed in the phone GUI. Thanks again for letting me know! :) 

Cheers!

**Comment by yha** [comment]
The new `Project.toml` seems to use a different UUID than the one `TSne.jl` is registered under. Is this UUID change intended?
This makes it currently impossible to do `]add TSne#master`

**Comment by simonschoelly** [comment]
No, this was my fault, I did not realize that the project already had a UUID in the general registry.  I will fix that.

**Comment by yha** [comment]
Also, what are the new compat bounds based on? Locally, I see that tests pass with `Distances` 0.8 (which I'm using because ImageSegmentation still caps the `Distances` version)

**Comment by simonschoelly** [comment]
I just added the newest compat bounds. To be honest, I am not really sure what is the best strategy here. Set it to `0.8.0`? Then it will be caped to versions  < `0.9.0`. Or maybe explicitly set it to `0.8.0, 0.9.0`?

**Comment by yha** [comment]
I think adding the newest compat bounds is a reasonable default, if it was tested on these versions. I just thought there might be some more specific reason, because there are bounds only for some of the dependencies, 
Based on the tests passing on my machine, I will set the Distances bounds to `0.8, 0.9` in a new PR.

**Pull request merged**
